### ISSUE TITLE
부하테스트 모니터링을 위해서 Prometheus + Grafana 연동

### ISSUE THREAD

**Issue by rookedsysc** [gamemuncheol/gamemuncheol-api#71]
## Goal 

부하테스트 모니터링을 위해서 Prometheus + Grafana 연동

## Reference 

- [Docker Compose.yaml](https://rookedsysc.vercel.app/java-and-spring/spring-boot/monitoring#docker-compose)
- [Prometheus Grafana 설정](https://velog.io/@roycewon/Spring-boot-%EB%AA%A8%EB%8B%88%ED%84%B0%EB%A7%81Prometheus-Grafana-docker)
- application.yaml 👉 [커밋](https://github.com/gamemuncheol/secret-file/commit/73337c82d4b6b28bccfa18c4f01090c41cd6dfa2) 참조

**Comment by rookedsysc** [comment]
```yaml
# docker-compose-monitoring.yml
version: '3'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: "$UID:$GID"
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-data:/var/lib/grafana
    depends_on:
      - prometheus

```
